export const lightTheme = {
  background:    '#f5f7f2',
  card:          '#ffffff',
  text:          '#1a1a1a',
  textSecondary: '#4a5568',
  textMuted:     '#6b705c',
  border:        '#e8eee4',
  primary:       '#2d6a4f',
  primaryLight:  '#d8f3dc',
  surface:       '#f8f9fa',
  danger:        '#e63946',
  warning:       '#ffb703',
  warningText:   '#1b1b1b',
  info:          '#0a558c',
  infoBackground:'#e0f0ff',
  inputBg:       '#ffffff',
  inputBorder:   '#b7e4c7',
  overlay:       'rgba(0,0,0,0.35)',
  tabBarBg:      '#ffffff',
  tabBarBorder:  '#e8eee4',
};

export const darkTheme = {
  background:    '#0f1a0f',
  card:          '#1a2d1a',
  text:          '#e8f5e9',
  textSecondary: '#9cbe9e',
  textMuted:     '#5a7a5c',
  border:        '#2a3d2a',
  primary:       '#6abf7a',
  primaryLight:  '#1a3d25',
  surface:       '#162116',
  danger:        '#ef5350',
  warning:       '#ffb703',
  warningText:   '#1b1b1b',
  info:          '#42a5f5',
  infoBackground:'#0d2d3f',
  inputBg:       '#162116',
  inputBorder:   '#2a3d2a',
  overlay:       'rgba(0,0,0,0.6)',
  tabBarBg:      '#0f1a0f',
  tabBarBorder:  '#2a3d2a',
};

export type Theme = typeof lightTheme;
