export const lightTheme = {
  background:    '#f5f7f2',
  card:          '#ffffff',
  cardAlt:       '#f8f9fa',
  text:          '#1a1a1a',
  textSecondary: '#6b705c',
  textMuted:     '#aaaaaa',
  border:        '#e9ecef',
  borderLight:   '#b7e4c7',
  primary:       '#2d6a4f',
  primaryDark:   '#1b4332',
  primaryLight:  '#d8f3dc',
  primaryBg:     '#f1f8f3',
  danger:        '#e63946',
  dangerLight:   '#fff5f5',
  warning:       '#ffb703',
  warningLight:  '#fff9e6',
  info:          '#3a86ff',
  infoLight:     '#e0f0ff',
  overlay:       'rgba(0,0,0,0.45)',
};

export const darkTheme: typeof lightTheme = {
  background:    '#0f1a0f',
  card:          '#1a2d1a',
  cardAlt:       '#1e2e1e',
  text:          '#e8f5e9',
  textSecondary: '#9cbe9e',
  textMuted:     '#5a7a5c',
  border:        '#2a3d2a',
  borderLight:   '#2a5c3a',
  primary:       '#52b788',
  primaryDark:   '#74c69d',
  primaryLight:  '#1a3d25',
  primaryBg:     '#0f2a18',
  danger:        '#ff6b6b',
  dangerLight:   '#2d1010',
  warning:       '#ffd166',
  warningLight:  '#2a2010',
  info:          '#74b9ff',
  infoLight:     '#0d1a2d',
  overlay:       'rgba(0,0,0,0.65)',
};

export type Theme = typeof lightTheme;
