import { relativeDueLabel, toLocalNoonISO, addDaysISO, shortDate, fullDateTime } from './dateUtils';

describe('toLocalNoonISO', () => {
  it('anchors the ISO timestamp at local noon on the given calendar day', () => {
    const input = new Date(2026, 5, 14, 23, 45); // 14 June 2026, 23:45 local time
    const iso = toLocalNoonISO(input);
    const result = new Date(iso);
    expect(result.getFullYear()).toBe(2026);
    expect(result.getMonth()).toBe(5);
    expect(result.getDate()).toBe(14);
    expect(result.getHours()).toBe(12);
    expect(result.getMinutes()).toBe(0);
  });

  it('round-trips back to the same calendar day for any realistic timezone offset', () => {
    // Local noon is at least 12h away from both UTC-12 and UTC+14 boundaries,
    // so converting to UTC and reading it back in any timezone keeps the same day.
    const input = new Date(2026, 0, 1, 8, 0); // 1 Jan 2026, 08:00 local
    const iso = toLocalNoonISO(input);
    const utcHour = new Date(iso).getUTCHours();
    // Local noon shifted to UTC must stay within [0, 23] on the same UTC date
    // for offsets between UTC-12 and UTC+12 (and within one day for the rest).
    expect(utcHour).toBeGreaterThanOrEqual(0);
    expect(utcHour).toBeLessThan(24);
  });
});

describe('addDaysISO', () => {
  it('returns an ISO timestamp for "today" when days is 0', () => {
    const iso = addDaysISO(0);
    const result = new Date(iso);
    const now = new Date();
    expect(result.getFullYear()).toBe(now.getFullYear());
    expect(result.getMonth()).toBe(now.getMonth());
    expect(result.getDate()).toBe(now.getDate());
    expect(result.getHours()).toBe(12);
  });

  it('returns a date N calendar days in the future, anchored at local noon', () => {
    const todayIso = addDaysISO(0);
    const futureIso = addDaysISO(7);
    const today = new Date(todayIso);
    const future = new Date(futureIso);
    const diffDays = Math.round((future.getTime() - today.getTime()) / 86_400_000);
    expect(diffDays).toBe(7);
    expect(future.getHours()).toBe(12);
  });
});

describe('relativeDueLabel', () => {
  it('labels a date generated by addDaysISO(0) as "Vandaag"', () => {
    expect(relativeDueLabel(addDaysISO(0))).toBe('Vandaag');
  });

  it('labels a date generated by addDaysISO(1) as "Morgen"', () => {
    expect(relativeDueLabel(addDaysISO(1))).toBe('Morgen');
  });

  it('labels a date generated by addDaysISO(2) as "Overmorgen"', () => {
    expect(relativeDueLabel(addDaysISO(2))).toBe('Overmorgen');
  });

  it('labels a date generated by addDaysISO(5) as "Over 5 dagen"', () => {
    expect(relativeDueLabel(addDaysISO(5))).toBe('Over 5 dagen');
  });

  it('labels a date generated by addDaysISO(-1) as "Gisteren"', () => {
    expect(relativeDueLabel(addDaysISO(-1))).toBe('Gisteren');
  });

  it('labels a date generated by addDaysISO(-4) as "4 dagen geleden"', () => {
    expect(relativeDueLabel(addDaysISO(-4))).toBe('4 dagen geleden');
  });
});

describe('shortDate / fullDateTime', () => {
  it('formats a date in Dutch short form', () => {
    const iso = toLocalNoonISO(new Date(2026, 4, 26)); // 26 May 2026
    expect(shortDate(iso)).toMatch(/26 mei/);
  });

  it('formats a date+time in Dutch, including "om"', () => {
    const iso = toLocalNoonISO(new Date(2026, 4, 26));
    expect(fullDateTime(iso)).toMatch(/26 mei om \d{2}:\d{2}/);
  });
});
